version: '3'

services:
  youtube:
    restart: always
    ports:
      - "8001:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=youtube00e1f862e5eff
    deploy:
      resources:
        limits:
          memory: 4G
  weibo:
    restart: always
    ports:
      - "8002:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=wei223be19ab11e891bo
    deploy:
      resources:
        limits:
          memory: 4G
  rss:
    restart: always
    ports:
      - "8003:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=rss007d0675444aa13fc
    deploy:
      resources:
        limits:
          memory: 4G
  hn:
    restart: always
    ports:
      - "8004:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=hackbc9419ab11eebe56
    deploy:
      resources:
        limits:
          memory: 4G
  4chan:
    restart: always
    ports:
      - "8005:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=ch4875eda56be56000ac
    deploy:
      resources:
        limits:
          memory: 4G
  reddit:
    restart: always
    ports:
      - "8006:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=ap98j3envoubi3fco1kc
    deploy:
      resources:
        limits:
          memory: 4G
  forocoches:
    restart: always
    ports:
      - "8007:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=forocoches86019fc2d4
    deploy:
      resources:
        limits:
          memory: 4G
  followin:
    restart: always
    ports:
      - "8008:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=followinc645fc950d7f
    deploy:
      resources:
        limits:
          memory: 4G
  twitter:
    restart: always
    ports:
      - "8009:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=a7df32de3a60dfdb7a0b
      - SCWEET_EMAIL=b79187429@gmail.com
      - SCWEET_USERNAME=Bob478089434267
      - SCWEET_PASSWORD=moule05moule05
    deploy:
      resources:
        limits:
          memory: 4G
  jvc:
    restart: always
    ports:
      - "8010:8000"
    build:
      dockerfile: ./scrap/Dockerfile
    init: true
    working_dir: /app/
    command: python3.10 /app/scraper.py
    environment:
      - PORT=8000
      - scraper_module=jvc8439846094ced03ff
