
on:
  repository_dispatch:
    types: [trigger-build-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the module name
        run: |
          echo "Module Name: ${{ github.event.client_payload.moduleName }}"

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "./Dockerfile"
          build-args: |
            "RELEASE_VERSION=${{ github.event.release.tag_name || github.ref }}"
            "MODULE_NAME=${{ github.event.client_payload.moduleName }}"
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            exordelabs/${{ github.event.client_payload.moduleName }}:${{ github.event.release.tag_name || github.ref }}
            exordelabs/${{ github.event.client_payload.moduleName }}:latest
