name: Build & Publish

on:
  repository_dispatch:
    types: [trigger-build-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Latest Release
        id: get-latest-release
        run: |
          LATEST_RELEASE_JSON=$(curl -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest")
          LATEST_RELEASE_TAG=$(echo $LATEST_RELEASE_JSON | jq -r .tag_name)
          echo "Latest release tag is $LATEST_RELEASE_TAG"
          echo "LATEST_RELEASE_TAG=$LATEST_RELEASE_TAG" >> $GITHUB_ENV

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push ${{ github.event.client_payload.moduleName }}
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "./Dockerfile"
          build-args: |
            RELEASE_VERSION=${{ env.LATEST_RELEASE_TAG }}.${{ github.event.client_payload.moduleTag }}
            MODULE_NAME=${{ github.event.client_payload.moduleName }}
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            exordelabs/spot${{ github.event.client_payload.moduleName }}:${{ env.LATEST_RELEASE_TAG }}.${{ github.event.client_payload.moduleTag }}
            exordelabs/spot${{ github.event.client_payload.moduleName }}:latest
